<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lazDar">
    <xacro:property name="base_radius" value="0.005"/>
    <xacro:property name="base_height" value="0.005"/>
    <xacro:property name="laz_radius" value="0.004"/>
    <xacro:property name="laz_height" value="0.01"/>
    <xacro:property name="mass" value="0.001"/>

    <gazebo reference="laz_base">
        <material>Gazebo/Grey</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <link name="laz_base">
        <visual>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="${(1/12) * mass * (3 * base_radius * base_radius + base_height * base_height)}" ixy="0" ixz="0" iyy="${(1/12) * mass * (3 * base_radius * base_radius + base_height * base_height)}" iyz="0" izz="${(1/2) * mass * base_radius * base_radius}"/>
        </inertial>
    </link>


    <link name="laz_rot">
        <visual>
            <geometry>
              <cylinder length="${laz_height}" radius="${laz_radius}"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
              <cylinder length="${laz_height}" radius="${laz_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="${(1/12) * mass * (3 * laz_radius * laz_radius + laz_height * laz_height)}" ixy="0" ixz="0" iyy="${(1/12) * mass * (3 * laz_radius * laz_radius + laz_height * laz_height)}" iyz="0" izz="${(1/2) * mass * laz_radius * laz_radius}"/>
        </inertial>
    </link>

    <joint name="joint_rotational_2d_lidar" type="continuous">
        <parent link="laz_base"/>
        <child link="laz_rot"/>
        <axis xyz="0 0 1"/>
        <origin xyz = "0 0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
        <dynamics friction="0.1"/>
    </joint>

    <joint name="joint_2d_lidar" type="fixed">
      <parent link="body"/>
      <child link="laz_base"/>
      <origin xyz="0.25 0.075 0.028605" rpy="0.0 0.0 0.0"/>
    </joint>

    <gazebo reference="laz_rot">
        <material>Gazebo/RedGlow</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>

        <sensor type="ray" name="laz">
            <pose>${laz_radius} 0 ${laz_height/4} 0 0 0</pose>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>100</samples>
                        <resolution>1</resolution>
                        <min_angle>-${pi/8}</min_angle>
                        <max_angle>${pi/8}</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>1</samples>
                        <resolution>1</resolution>
                        <min_angle>0</min_angle>
                        <max_angle>0</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.05</min>
                    <max>15</max>
                    <resolution>0.02</resolution>
              </range>
            </ray>

            <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
                <output_type>sensor_msgs/LaserScan</output_type>
                <topicName>/laser/scan</topicName>
                <frameName>laz_rot</frameName>
            </plugin>
        </sensor>
        
    </gazebo>
</robot>